[program:alarm-mqtt-action]
command=/usr/bin/alarm-mqtt-action.sh
autostart=true
autorestart=true
startretries=3
startsecs=10
stderr_logfile=/var/log/alarm-mqtt-action.err.log
stdout_logfile=/var/log/alarm-mqtt-action.out.log
