[program:alarm-publish-video]
command=/usr/bin/alarm-publish-video-action.sh
autostart=true
autorestart=true
startretries=9999
startsecs=10
stderr_logfile=/var/log/alarm-publish-video.err.log
stdout_logfile=/var/log/alarm-publish-video.out.log
