[program:alarm-record-video]
command=/usr/bin/alarm-record-video.sh
autostart=true
autorestart=unexpected
exitcodes=123
startretries=9999
startsecs=0
stopasgroup=true
killasgroup=true
stderr_logfile=/var/log/alarm-record-video.err.log
stdout_logfile=/var/log/alarm-record-video.out.log
