[program:alarm-extract-video]
command=/usr/bin/alarm-mqtt-action.sh
autostart=true
autorestart=true
startretries=3
startsecs=10
stderr_logfile=/var/log/alarm-extract-video.err.log
stdout_logfile=/var/log/alarm-extract-video.out.log
